port: 3000
loglevel: info
persist: true
mongodburl: mongodb://myusername:mypassword@mongo1-mongodb-replicaset-0.mongo-mongodb-replicaset,mongo-mongodb-replicaset-1.mongo-mongodb-replicaset,mongo-mongodb-replicaset-2.mongo-mongodb-replicaset:27017/echo?authSource=admin
dbname: echo

